pieces_keywords = {
    "Performance": [
        "speed", "response time", "throughput", "availability",
        "Response time", "System speed", "Load time", "Processing speed",
        "Throughput", "Latency", "System performance", "Performance optimization",
        "Scalability", "System efficiency", "Application speed", "Network performance",
        "Bandwidth usage", "Performance tuning", "Resource utilization", "Data processing speed",
        "Real-time processing", "Query performance", "Response rate", "Speed optimization",
        "Server response", "Performance metrics", "Page load speed", "Application performance",
        "System responsiveness", "Data throughput", "Network latency", "Response efficiency",
        "Performance monitoring", "Load balancing", "Database performance", "High availability",
        "System benchmarking", "Performance analysis", "Optimization techniques", "Speed benchmarks",
        "System load handling", "Task execution time", "Performance degradation", "Network throughput",
        "System lag", "Application latency", "Performance bottlenecks", "Speed improvement",
        "Processing efficiency", "Server speed", "Query speed", "System downtime",
        "Data retrieval speed", "Load capacity", "Peak performance", "Performance testing",
        "Computational speed", "Network speed", "Performance evaluation", "Application responsiveness",
        "Performance benchmarks", "Throughput measurement", "Speed metrics", "Real-time speed",
        "Performance consistency", "Load time reduction", "Server performance", "Resource efficiency",
        "Speed analysis", "Performance improvement", "Task performance", "Response optimization",
        "Performance metrics tracking", "Network performance tuning", "Data processing optimization",
        "Response speed", "System acceleration", "Performance scalability", "Application load speed",
        "System speed enhancement", "Real-time performance", "Performance feedback", "Response improvement",
        "Performance diagnostics", "Speed troubleshooting", "Performance indicators", "Speed metrics analysis",
        "System throughput", "Speed enhancement", "Load speed optimization", "Processing speed improvement",
        "Performance stability", "Application efficiency", "System latency reduction", "Performance upgrades",
        "Throughput optimization", "Response enhancement", "Application throughput", "System performance metrics",
        "Real-time performance tracking", "Performance measurement tools", "Data throughput enhancement",
        "Network speed improvement", "System performance tuning"
    ],
    "Information": [
        "accuracy", "relevance", "timeliness", "completeness",
        "Data accuracy", "Information quality", "Data completeness", 
        "Data relevance", "Data security", "Information integrity", 
        "Data availability", "Data consistency", "Data reliability", 
        "Data validity", "Information accuracy", "Data protection", 
        "Data confidentiality", "Data integration", "Information retrieval", 
        "Data usability", "Information accessibility", "Data governance", 
        "Data standardization", "Information management", "Data privacy", 
        "Data verification", "Data authentication", "Data validation", 
        "Data cleansing", "Data storage", "Data encryption", 
        "Data backup", "Data recovery", "Data lifecycle", 
        "Data archiving", "Data classification", "Data ownership", 
        "Data stewardship", "Data audit", "Data provenance", 
        "Data lineage", "Data discovery", "Data profiling", 
        "Data governance framework", "Data security standards", 
        "Data protection regulations", "Data compliance", 
        "Data governance policies", "Data governance best practices", 
        "Data management", "Information security", "Data governance tools", 
        "Data governance strategy", "Data governance implementation", 
        "Data governance framework", "Data governance processes", 
        "Data governance principles", "Data governance guidelines", 
        "Data governance assessment", "Data governance maturity model", 
        "Data governance roadmap", "Data governance metrics", 
        "Data governance controls", "Data governance framework components", 
        "Data governance roles", "Data governance responsibilities", 
        "Data governance training", "Data governance communication", 
        "Data governance collaboration", "Data governance enforcement", 
        "Data governance monitoring", "Data governance reporting", 
        "Data governance review", "Data governance improvement", 
        "Data governance alignment", "Data governance transparency", 
        "Data governance accountability", "Data governance risk management", 
        "Data governance audit", "Data governance compliance", 
        "Data governance privacy", "Data governance security", 
        "Data governance quality", "Data governance lifecycle", 
        "Data governance architecture", "Data governance controls", 
        "Data governance maturity", "Data governance integration", 
        "Data governance documentation", "Data governance metadata", 
        "Data governance metrics", "Data governance frameworks", 
        "Data governance governance", "Data governance access control", 
        "Data governance data quality", "Data governance decision making", 
        "Data governance stewardship"
    ],
    "Economics": [
        "cost", "benefit", "value", "return on investment", "Cost efficiency", 
        "Operational cost", "Budget management", "Cost-benefit analysis", 
        "Return on Investment", "Cost reduction", "Expense control", 
        "Financial efficiency", "Cost optimization", "Cost-saving measures", 
        "Investment return", "Budget optimization", "Economic feasibility", 
        "Cost management", "Financial planning", "Cost analysis", 
        "Expenditure reduction", "Budget efficiency", "Financial performance", 
        "Cost-effectiveness", "Budget allocation", "Financial management", 
        "Cost control", "Cost savings", "Profitability", "Revenue generation", 
        "Financial analysis", "Expense management", "Capital expenditure", 
        "Operating expenses", "Capital investment", "Budgetary control", 
        "Cost containment", "Financial sustainability", "Cost structure", 
        "Cost allocation", "Budgetary planning", "Cost tracking", 
        "Revenue management", "Profit maximization", "Cost monitoring", 
        "Resource optimization", "Cost forecasting", "Budget forecasting", 
        "Expense tracking", "Financial forecasting", "Budgetary forecasting", 
        "Cost estimation", "Revenue forecasting", "Investment analysis", 
        "Financial modeling", "Cost projection", "Profit margin", 
        "Break-even analysis", "Return on Capital Employed (ROCE)", 
        "Net present value (NPV)", "Internal Rate of Return (IRR)", 
        "Payback period", "Cost-benefit ratio", "Financial viability", 
        "Financial risk management", "Financial health", 
        "Financial decision-making", "Financial control", 
        "Financial efficiency", "Financial reporting", "Financial governance", 
        "Financial audit", "Financial compliance", "Financial accountability", 
        "Financial transparency", "Financial stability", "Financial strategy", 
        "Financial policy", "Financial regulation", "Financial performance measurement", 
        "Financial benchmarking", "Financial metrics", "Financial controls", 
        "Financial processes", "Financial systems", "Financial tools", 
        "Financial standards", "Financial best practices", "Financial guidelines", 
        "Financial procedures", "Financial protocols", "Financial frameworks", 
        "Financial systems integration", "Financial system architecture", 
        "Financial system design", "Financial system implementation", 
        "Financial system optimization", "Financial system performance"
    ],
    "Control": [
        "security", "privacy", "compliance", "audit", "Access control", 
        "Data security", "Compliance", "Authorization", "Audit trails", 
        "Risk management", "Security protocols", "Access management", 
        "User authentication", "Data privacy", "Security policies", 
        "Regulatory compliance", "Control mechanisms", "Security management", 
        "Information security", "Access rights", "Fraud prevention", 
        "Control systems", "Data audit", "Security controls", 
        "Security standards", "Access policies", "Security procedures", 
        "Security guidelines", "Access monitoring", "User authorization", 
        "Security measures", "Security enforcement", "Identity management", 
        "Authentication methods", "Authorization protocols", "Security compliance", 
        "Data protection laws", "Identity verification", "Access restrictions", 
        "User access", "Security architecture", "Access security", 
        "Security infrastructure", "Data encryption", "Security assessments", 
        "Data integrity", "Identity authentication", "Security audits", 
        "Data protection regulations", "Data confidentiality", 
        "Access rights management", "Security best practices", "Access controls", 
        "Data security measures", "Identity access management", "Access permissions", 
        "Security solutions", "Security frameworks", "Access policies", 
        "Security enforcement", "Data security policies", "Access governance", 
        "Security awareness", "Security implementation", 
        "Data protection mechanisms", "Data security standards", 
        "Data protection protocols", "Security governance", 
        "Data security practices", "Security guidelines", "Data access control", 
        "Security risk assessment", "Data security management", "Security procedures", 
        "Data protection practices", "Security protocols", "Data security controls", 
        "Access management systems", "Security measures", 
        "Data security enforcement", "Security strategies", 
        "Security controls implementation", "Data access management", 
        "Data security guidelines", "Security compliance standards", 
        "Data protection strategies", "Data security enforcement", 
        "Security technologies", "Security architecture design", 
        "Data protection frameworks", "Data security processes", "Access control policies", 
        "Security assessment methods", "Data security monitoring", 
        "Security incident management"
        ],
    "Efficiency": [
        "Resource utilization", "Process efficiency", "Workflow optimization",
        "Time management", "Productivity", "Resource allocation",
        "Operational efficiency", "Task automation", "Efficiency improvement",
        "Resource efficiency", "Time optimization", "Workflow efficiency",
        "Efficiency measurement", "Performance efficiency", "System optimization",
        "Task efficiency", "Resource planning", "Efficiency analysis",
        "Process optimization", "Resource management", "Time efficiency",
        "Efficiency metrics", "Workflow automation", "Efficiency tools",
        "Efficiency strategies", "Efficiency gains", "Resource optimization",
        "Process automation", "Operational optimization", "Time-saving",
        "Workforce optimization", "Efficiency enhancement", "Efficiency standards",
        "Operational effectiveness", "Efficiency initiatives", "Efficiency solutions",
        "Workforce efficiency", "Workflow management", "Process improvement",
        "Efficiency evaluation", "Operational excellence", "Efficiency benchmarks",
        "Workflow analysis", "Efficiency monitoring", "Process management",
        "Time-saving techniques", "Efficiency programs", "Process standardization",
        "Workforce productivity", "Workflow streamlining", "Efficiency assessment",
        "Resource utilization optimization", "Operational streamlining",
        "Time-saving strategies", "Task optimization", "Workforce management",
        "Efficiency optimization", "Workflow efficiency", "Resource efficiency improvement",
        "Process efficiency enhancement", "Time management techniques", "Productivity improvement",
        "Task management", "Workload optimization", "Efficiency metrics tracking",
        "Resource allocation optimization", "Workflow optimization strategies",
        "Operational efficiency improvement", "Task automation",
        "Resource optimization techniques", "Process efficiency analysis",
        "Time management skills", "Workforce optimization strategies",
        "Efficiency measurement tools", "Resource allocation strategies",
        "Workflow efficiency improvement", "Operational efficiency optimization",
        "Task prioritization", "Resource utilization analysis",
        "Process optimization techniques", "Time management optimization",
        "Productivity enhancement", "Task prioritization techniques",
        "Workforce efficiency improvement", "Efficiency metrics measurement",
        "Resource allocation analysis", "Workflow efficiency analysis",
        "Operational efficiency enhancement", "Task efficiency improvement",
        "Resource utilization assessment", "Process efficiency improvement",
        "Time management optimization strategies"
        ],
        "Service": [
        "Service convenience", "Service planning", "Service feedback",
        "Service development", "User satisfaction", "Service adaptation",
        "Service performance", "Customer experience", "Service monitoring",
        "Service reputation", "Service assurance", "Service scalability",
        "Customer support", "Customer service", "Service innovation",
        "Service integration", "Service alignment", "Customer satisfaction",
        "Service personalization", "Service communication", "Service timeliness",
        "Service flexibility", "Service enhancement", "Service efficiency",
        "Service sustainability", "Service consistency", "Service optimization",
        "Service availability", "Service delivery", "Service customization",
        "Service partnership", "Service trust", "Service quality",
        "Service excellence", "Service accessibility", "Service accountability",
        "Service management", "Service improvement", "Service standards",
        "Service strategy", "Service transparency", "Service agility",
        "Service satisfaction", "Service responsiveness", "Service loyalty",
        "Service reliability", "Service commitment", "User experience",
        "Service evaluation", "Service interaction", "Service collaboration",
        "Service effectiveness", "Performance", "Response time", "System speed",
        "Load time", "Processing speed", "Latency", "System performance",
        "Performance optimization", "Scalability", "System efficiency",
        "Application speed", "Network performance", "Performance tuning",
        "Resource utilization", "Data processing speed", "Real-time processing",
        "Query performance", "Response rate", "Speed optimization",
        "Server response", "Performance metrics", "Page load speed",
        "Application performance", "System responsiveness", "Data throughput",
        "Network latency", "Response efficiency", "Performance monitoring",
        "Load balancing", "Database performance", "High availability",
        "System benchmarking", "Performance analysis", "Optimization techniques",
        "Speed benchmarks", "System load handling", "Task execution time",
        "Performance degradation", "Network throughput", "System lag",
        "Application latency", "Performance bottlenecks", "Speed improvement",
        "Processing efficiency", "Server speed", "Query speed",
        "System downtime", "Data retrieval speed", "Load capacity",
        "Peak performance", "Performance testing", "Computational speed",
        "Network speed", "Performance evaluation", "Application responsiveness",
        "Performance benchmarks", "Throughput measurement", "Speed metrics",
        "Real-time speed", "Performance consistency", "Load time reduction",
        "Server performance", "Resource efficiency", "Speed analysis",
        "Performance improvement", "Task performance", "Response optimization",
        "Performance metrics tracking", "Network performance tuning",
        "Data processing optimization", "Response speed", "System acceleration",
        "Performance scalability", "Application load speed",
        "System speed enhancement", "Real-time performance", "Performance feedback",
        "Response improvement", "Performance diagnostics", "Speed troubleshooting",
        "Performance indicators", "Speed metrics analysis", "System throughput",
        "Speed enhancement", "Load speed optimization", "Processing speed improvement",
        "Performance stability", "Application efficiency", "System latency reduction",
        "Performance upgrades", "Throughput optimization", "Response enhancement",
        "Application throughput", "System performance metrics",
        "Real-time performance tracking", "Performance measurement tools",
        "Data throughput enhancement", "Network speed improvement",
        "System performance tuning"
        ]
    }